### ISSUE TITLE
Having problem in running the powershell code

### ISSUE THREAD

**Issue by elagrija** [mantvydasb/Invoke-PowerCloud#1]
![powercloud](https://user-images.githubusercontent.com/13571168/47660161-7189f000-dbbc-11e8-933a-93ab4d93220b.PNG)

My query is .. what is meant by . .\powercloud.ps1...

**Comment by mantvydasb** [comment]
Hey, thanks for the question.

If you change powecloud.ps1 to Invoke-PowerCloud.ps1 it should be good to go. Powercloud.ps1 was the working name of the script, which later got changed to Invoke-PowerCloud.ps1.

Let me me know how it goes.

**Comment by elagrija** [comment]
Hey Bro

It is working fine when changed powecloud.ps1 to Invoke-PowerCloud.ps1

PFB  the same

 .\Invoke-PowerCloud.ps1; Invoke-PowerCloud -FilePath payloadd.txt -Domain redteam.me -Verbose

And may i pls know... 

1. what does the following doing here in the above mentioned command
 
    Invoke-PowerCloud -FilePath mypayloadd.txt

  and why the following is not running

.\Invoke-PowerCloud.ps1 -FilePath payloadd.txt -Domain redteam.me -Verbose

 Can you explain a little bit to us to understand better

**Comment by elagrija** [comment]
Also .. I got so many Exceptions , but in the end stagers has been generated. 





Do you have any Suggestions to overcome the exceptions .
I yet not checked the final stagers execution.
![exception](https://user-images.githubusercontent.com/13571168/47789855-bdaf6e80-dd3b-11e8-9971-c8edaad111a7.PNG)

**Comment by mantvydasb** [comment]
In the command "Invoke-PowerCloud -FilePath payloadd.txt -Domain redteam.me -Verbose" 
-FilePath is the path to a file that contains your powershell payload you want to deliver.
-Domain is YOUR domain that is managed by the cloudflare. Note that you need to specify your  cloudflare API and your email address you use to login to cloudflare - in the script as explained in the article you read.

First of all, you are getting these errors because you are trying to use my domain redteam.me - this will not work as mentioned above :)

hope it helps

**Comment by elagrija** [comment]
Yea got it bro
